import React, { useState, useEffect } from 'react';
import { ItineraryDay, AppMode } from '../types';
import { Share2, Lock, Star, Sun, Moon, Coffee, Map, Printer, Check, FileText, Camera } from 'lucide-react';
import Lottie from 'lottie-react';

interface ItineraryViewProps {
  itinerary: ItineraryDay[];
  mode: AppMode;
  isLoading: boolean;
  onGenerate: () => void;
  isPro: boolean;
  onUpgrade: () => void;
}

const ItineraryView: React.FC<ItineraryViewProps> = ({ 
  itinerary, 
  mode, 
  isLoading, 
  onGenerate,
  isPro,
  onUpgrade
}) => {
  const isKid = mode === AppMode.KID;
  const [selectedDayIndex, setSelectedDayIndex] = useState(0);
  const [copied, setCopied] = useState(false);
  const [showConfetti, setShowConfetti] = useState(false);
  const [confettiData, setConfettiData] = useState<any>(null);

  // Fetch Confetti Lottie Data
  useEffect(() => {
    // A standard confetti burst animation
    fetch('https://lottie.host/88ac83b6-2035-4200-8802-997c413a2322/2V1sg3K9rA.json')
      .then(res => res.json())
      .then(data => setConfettiData(data))
      .catch(err => console.error("Failed to load confetti", err));
  }, []);

  // Trigger confetti when itinerary is generated (length goes from 0 to N)
  useEffect(() => {
    if (itinerary.length > 0 && !isLoading) {
      setShowConfetti(true);
      // Confetti usually lasts a few seconds
      const timer = setTimeout(() => {
        setShowConfetti(false);
      }, 5000);
      return () => clearTimeout(timer);
    }
  }, [itinerary.length, isLoading]);

  const handleShare = async () => {
    const title = `Magic Passport: ${itinerary.length}-Day Plan`;
    const header = `🗺️ *${title}*\nHere is our adventure passport!`;
    
    const body = itinerary.map(d => 
      `*Day ${d.day} (${d.dayLabel})*\n` +
      `🌞 ${d.morning.title}\n` +
      `🥗 ${d.lunch.title}\n` +
      `🏃 ${d.afternoon.title}\n` +
      `🌙 ${d.evening.title}`
    ).join('\n\n------------------\n\n');

    const fullText = `${header}\n\n${body}\n\nGenerated by Kidventour 🚀`;

    if (navigator.share) {
      try {
        await navigator.share({
          title: title,
          text: fullText,
        });
      } catch (err) {
        console.log('Share cancelled');
      }
    } else {
      try {
        await navigator.clipboard.writeText(fullText);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      } catch (err) {
        alert("Could not copy to clipboard.");
      }
    }
  };

  const handlePrint = () => {
    window.print();
  };

  // Loading State
  if (isLoading) {
    return (
      <div className="h-full flex flex-col items-center justify-center p-8 text-center bg-slate-50">
        <div className={`w-16 h-16 border-4 border-t-transparent rounded-full animate-spin mb-4 ${isKid ? 'border-purple-500' : 'border-mint-500'}`}></div>
        <h3 className={`text-xl font-bold mb-2 ${isKid ? 'text-purple-600' : 'text-slate-800'}`}>
          {isKid ? 'Printing Passport...' : 'Creating Magic Passport...'}
        </h3>
        <p className="text-slate-500 text-sm">Stamping pages, checking weather...</p>
      </div>
    );
  }

  // Not Pro / Paywall State
  if (!isPro && itinerary.length === 0) {
    return (
      <div className="h-full flex flex-col items-center justify-center p-6 text-center bg-slate-50">
        <div className="w-24 h-24 bg-gradient-to-tr from-yellow-300 to-yellow-500 rounded-full shadow-lg flex items-center justify-center mb-6 text-white animate-pulse relative">
          <Star size={40} fill="currentColor" />
          <div className="absolute -bottom-2 -right-2 bg-purple-600 text-white text-[10px] font-bold px-2 py-1 rounded-full border-2 border-white">PRO</div>
        </div>
        <h2 className="text-2xl font-bold text-slate-800 mb-2">Magic Month Passport</h2>
        <p className="text-slate-500 mb-8 max-w-xs leading-relaxed">
          Get a full 14-day holiday itinerary with automated shopping lists and rainy-day swaps.
        </p>
        
        <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-100 w-full max-w-sm mb-6 text-left relative overflow-hidden">
          {/* Faux stamp watermark */}
          <div className="absolute -right-4 -top-4 opacity-10 transform rotate-12 pointer-events-none">
             <div className="border-4 border-slate-900 rounded-full w-24 h-24 flex items-center justify-center font-black text-xs">APPROVED</div>
          </div>

          <ul className="space-y-3 relative z-10">
            <li className="flex items-center gap-3 text-sm text-slate-600">
              <span className="w-6 h-6 rounded-full bg-mint-100 text-mint-600 flex items-center justify-center text-xs">✓</span>
              PDF Passport Export
            </li>
            <li className="flex items-center gap-3 text-sm text-slate-600">
              <span className="w-6 h-6 rounded-full bg-mint-100 text-mint-600 flex items-center justify-center text-xs">✓</span>
              Shopping Checklists
            </li>
            <li className="flex items-center gap-3 text-sm text-slate-600">
              <span className="w-6 h-6 rounded-full bg-mint-100 text-mint-600 flex items-center justify-center text-xs">✓</span>
              Rainy-Day Auto-Swaps
            </li>
          </ul>
        </div>

        <button 
          onClick={onUpgrade}
          className="bg-slate-900 text-white font-bold py-4 px-8 rounded-xl shadow-lg hover:bg-slate-800 transition-colors w-full max-w-xs flex items-center justify-center gap-2 mb-4"
        >
          <Lock size={18} />
          Unlock Passport ($9.99)
        </button>

        <button className="text-xs font-bold text-purple-600 flex items-center gap-1 opacity-80 hover:opacity-100">
            <Camera size={14} /> Try 3-Day Trial with a Selfie
        </button>
      </div>
    );
  }

  // Initial Empty State (Pro but no plan yet)
  if (itinerary.length === 0) {
    return (
      <div className="h-full flex flex-col items-center justify-center p-8 text-center bg-slate-50">
        <div className="w-24 h-24 bg-white rounded-full shadow-sm flex items-center justify-center mb-6 relative">
          <span className="text-4xl">🗓️</span>
          <span className="absolute bottom-0 right-0 text-2xl animate-bounce">✨</span>
        </div>
        <h2 className="text-2xl font-bold text-slate-800 mb-2">Ready for Magic?</h2>
        <p className="text-slate-500 mb-8 max-w-xs">Create your family's 14-day master plan.</p>
        <button 
          onClick={onGenerate}
          className="bg-mint-500 text-white font-bold py-4 px-8 rounded-xl shadow-lg hover:bg-mint-600 transition-colors w-full max-w-xs"
        >
          Generate Passport ✨
        </button>
      </div>
    );
  }

  const activeDay = itinerary[selectedDayIndex];

  return (
    <div className="h-full flex flex-col bg-slate-50 relative">
      {/* Confetti Overlay */}
      {showConfetti && confettiData && (
        <div className="absolute inset-0 z-50 pointer-events-none flex items-start justify-center overflow-hidden">
          <Lottie 
            animationData={confettiData} 
            loop={false}
            style={{ width: '100%', height: '100%', maxWidth: 600 }}
          />
        </div>
      )}

      {/* Header & Day Strip */}
      <div className="bg-white shadow-sm z-10 no-print">
        <div className="p-4 pb-2 flex justify-between items-center bg-slate-800 text-white">
          <div>
            <h2 className={`text-xl font-display font-bold`}>
              Magic Passport
            </h2>
            <p className="text-xs text-slate-300 font-mono tracking-widest uppercase">
              ID: KID-VENTOUR-001
            </p>
          </div>
          <div className="flex gap-2">
            <button 
              onClick={handlePrint}
              className="p-2 bg-white/10 rounded-full hover:bg-white/20 hidden sm:flex"
              title="Print PDF"
            >
              <FileText size={18} />
            </button>
            <button 
              onClick={handleShare}
              className={`p-2 rounded-full transition-all ${copied ? 'bg-green-500 text-white' : 'bg-white/10 hover:bg-white/20'}`}
              title="Share"
            >
              {copied ? <Check size={18} /> : <Share2 size={18} />}
            </button>
          </div>
        </div>

        {/* Horizontal Day Scroller */}
        <div className="flex overflow-x-auto no-scrollbar py-3 px-4 gap-3 snap-x bg-slate-50 border-b border-slate-200">
          {itinerary.map((day, idx) => (
            <button
              key={day.day}
              onClick={() => setSelectedDayIndex(idx)}
              className={`flex-shrink-0 w-14 h-16 rounded-lg flex flex-col items-center justify-center transition-all snap-start border-2 ${
                selectedDayIndex === idx
                  ? 'bg-white border-slate-800 text-slate-900 shadow-md scale-105'
                  : 'bg-white border-slate-200 text-slate-400 opacity-70'
              }`}
            >
              <span className="text-xs font-semibold uppercase">{day.dayLabel}</span>
              <span className="text-lg font-black font-display">{day.day}</span>
            </button>
          ))}
        </div>
      </div>

      {/* Main Content Area - Passport Style */}
      <div className="flex-1 overflow-y-auto p-4 space-y-4 pb-24 print:overflow-visible print:h-auto bg-[url('https://www.transparenttextures.com/patterns/cream-paper.png')]">
        {activeDay && (
          <div className="max-w-2xl mx-auto space-y-4">
            
            {/* Stamp Header */}
            <div className="flex justify-between items-end px-2 opacity-50">
                <div className="text-xs font-mono uppercase text-slate-500">Entry: Day {activeDay.day}</div>
                <div className="border-2 border-slate-300 rounded-full w-12 h-12 flex items-center justify-center transform -rotate-12">
                    <Star size={16} className="text-slate-300" />
                </div>
            </div>

            {/* Morning */}
            <div className="bg-white p-4 rounded-lg border-2 border-slate-100 shadow-sm print:shadow-none print:border relative overflow-hidden group">
              <div className="absolute top-0 right-0 bg-orange-100 text-orange-700 text-[10px] font-bold px-2 py-0.5 rounded-bl-lg">9 AM</div>
              <div className="flex items-center gap-3 mb-2">
                <div className="w-8 h-8 rounded-full bg-orange-50 flex items-center justify-center text-orange-500">
                    <Sun size={18} />
                </div>
                <h3 className="font-bold text-slate-800 text-lg leading-tight">{activeDay.morning.title}</h3>
              </div>
              <p className="text-slate-600 text-sm pl-11">{activeDay.morning.description}</p>
            </div>

            {/* Lunch */}
            <div className="bg-white p-4 rounded-lg border-2 border-slate-100 shadow-sm print:shadow-none print:border relative overflow-hidden">
             <div className="absolute top-0 right-0 bg-mint-100 text-mint-700 text-[10px] font-bold px-2 py-0.5 rounded-bl-lg">12 PM</div>
              <div className="flex items-center gap-3 mb-2">
                <div className="w-8 h-8 rounded-full bg-mint-50 flex items-center justify-center text-mint-500">
                    <Coffee size={18} />
                </div>
                <h3 className="font-bold text-slate-800 text-lg leading-tight">{activeDay.lunch.title}</h3>
              </div>
              <p className="text-slate-600 text-sm pl-11">{activeDay.lunch.description}</p>
            </div>

            {/* Afternoon */}
            <div className="bg-white p-4 rounded-lg border-2 border-slate-100 shadow-sm print:shadow-none print:border relative overflow-hidden">
             <div className="absolute top-0 right-0 bg-blue-100 text-blue-700 text-[10px] font-bold px-2 py-0.5 rounded-bl-lg">2 PM</div>
              <div className="flex items-center gap-3 mb-2">
                <div className="w-8 h-8 rounded-full bg-blue-50 flex items-center justify-center text-blue-500">
                    <Map size={18} />
                </div>
                <h3 className="font-bold text-slate-800 text-lg leading-tight">{activeDay.afternoon.title}</h3>
              </div>
              <p className="text-slate-600 text-sm pl-11">{activeDay.afternoon.description}</p>
            </div>

            {/* Evening */}
            <div className="bg-indigo-900 text-white p-4 rounded-lg shadow-sm print:shadow-none print:border print:bg-white print:text-black relative overflow-hidden">
             <div className="absolute top-0 right-0 bg-indigo-800 text-indigo-200 text-[10px] font-bold px-2 py-0.5 rounded-bl-lg">7 PM</div>
              <div className="flex items-center gap-3 mb-2">
                <div className="w-8 h-8 rounded-full bg-indigo-800 flex items-center justify-center text-indigo-300">
                    <Moon size={18} />
                </div>
                <h3 className="font-bold text-lg leading-tight">{activeDay.evening.title}</h3>
              </div>
              <p className="text-indigo-200 text-sm pl-11 italic print:text-slate-500">"{activeDay.evening.description}"</p>
            </div>

            {/* Bottom Share CTA */}
            <div className="pt-4 pb-8 flex justify-center print:hidden">
              <button 
                onClick={handleShare}
                className="flex items-center gap-2 px-6 py-3 rounded-full text-sm font-bold bg-slate-900 text-white shadow-lg active:scale-95 transition-transform"
              >
                {copied ? <Check size={18} /> : <Share2 size={18} />}
                {copied ? "Copied!" : "Export Passport PDF"}
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default ItineraryView;